import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{margin: 0, padding: 0}}>
        <nav>
          <Navbar/>
        </nav>
        <main className='mt-10 sm:mt-20 lg:mt-28'>
          {children}
        </main>
      </body>
    </html>
  )
}
